#!/usr/bin/env tsx
// Copyright Ben Chatelain. Apache 2.0

/**
 * Generates typed language bindings from JSON Schema files.
 *
 * Collects schemas from:
 *   - `upstream/` (top-level .json files only)
 *   - `authored/` (.json files, excluding `_meta/`)
 *
 * For each target language (Go, TypeScript, Python, Rust), runs quicktype-core
 * to produce typed code and writes the output to `generated/<lang>/`.
 *
 * Languages whose output directory does not exist are silently skipped.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  InputData,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
  quicktype,
} from "quicktype-core";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");
const UPSTREAM_DIR = join(PROJECT_ROOT, "upstream");
const AUTHORED_DIR = join(PROJECT_ROOT, "authored");
const GENERATED_DIR =
  process.env["GENERATE_OUTPUT_DIR"] ?? join(PROJECT_ROOT, "generated");

// ---------------------------------------------------------------------------
// Language configuration
// ---------------------------------------------------------------------------

interface LanguageTarget {
  /** quicktype language identifier (must match a quicktype built-in name) */
  lang: "go" | "typescript" | "python" | "rust";
  /** Output file path relative to GENERATED_DIR */
  outputPath: string;
  /** quicktype rendererOptions */
  rendererOptions: Record<string, string>;
  /** Comment syntax for the generated-by header */
  commentHeader: string;
}

const LANGUAGES: readonly LanguageTarget[] = [
  {
    lang: "go",
    outputPath: "go/types.go",
    rendererOptions: { package: "claudeconfig" },
    commentHeader:
      "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
  },
  {
    lang: "typescript",
    outputPath: "ts/src/types.ts",
    rendererOptions: {},
    commentHeader:
      "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
  },
  {
    lang: "python",
    outputPath: "python/claude_config/types.py",
    rendererOptions: {},
    commentHeader:
      "# Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
  },
  {
    lang: "rust",
    outputPath: "rust/src/types.rs",
    rendererOptions: {},
    commentHeader:
      "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
  },
] as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Derives a PascalCase type name from a schema filename.
 *
 * Examples:
 *   settings.json       → Settings
 *   plugin-manifest.json → PluginManifest
 *   skill-frontmatter.json → SkillFrontmatter
 */
function deriveTypeName(filename: string): string {
  const base = filename.replace(/\.json$/, "");
  return base
    .split("-")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

/**
 * Collects schema entries from upstream/ (top-level .json only) and
 * authored/ (.json files, excluding _meta/).
 */
function collectSchemas(): Array<{ name: string; schema: string }> {
  const schemas: Array<{ name: string; schema: string }> = [];

  // Upstream: top-level .json files only
  if (existsSync(UPSTREAM_DIR)) {
    const entries = readdirSync(UPSTREAM_DIR, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".json")) {
        const filePath = join(UPSTREAM_DIR, entry.name);
        const typeName = deriveTypeName(entry.name);
        schemas.push({
          name: typeName,
          schema: readFileSync(filePath, "utf-8"),
        });
      }
    }
  }

  // Authored: .json files recursively, excluding _meta/
  if (existsSync(AUTHORED_DIR)) {
    collectAuthoredSchemas(AUTHORED_DIR, schemas);
  }

  return schemas;
}

function collectAuthoredSchemas(
  dir: string,
  schemas: Array<{ name: string; schema: string }>
): void {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip the _meta directory
      if (entry.name === "_meta") continue;
      collectAuthoredSchemas(fullPath, schemas);
    } else if (entry.isFile() && entry.name.endsWith(".json")) {
      const typeName = deriveTypeName(entry.name);
      schemas.push({
        name: typeName,
        schema: readFileSync(fullPath, "utf-8"),
      });
    }
  }
}

/**
 * Ensures the parent directory for a file path exists.
 */
function ensureParentDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

interface GenerationResult {
  lang: string;
  outputPath: string;
  action: "generated" | "skipped";
  typeCount?: number;
  reason?: string;
}

async function generateForLanguage(
  target: LanguageTarget,
  schemas: ReadonlyArray<{ name: string; schema: string }>
): Promise<GenerationResult> {
  const outputFile = join(GENERATED_DIR, target.outputPath);
  const outputDir = dirname(outputFile);

  // Skip if the output directory does not exist
  if (!existsSync(outputDir)) {
    return {
      lang: target.lang,
      outputPath: target.outputPath,
      action: "skipped",
      reason: `directory ${target.outputPath.split("/").slice(0, -1).join("/")} does not exist`,
    };
  }

  const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());

  for (const { name, schema } of schemas) {
    await schemaInput.addSource({ name, schema });
  }

  const inputData = new InputData();
  inputData.addInput(schemaInput);

  const result = await quicktype({
    inputData,
    lang: target.lang,
    rendererOptions: target.rendererOptions,
  });

  const content =
    target.commentHeader + "\n\n" + result.lines.join("\n") + "\n";

  ensureParentDir(outputFile);
  writeFileSync(outputFile, content);

  return {
    lang: target.lang,
    outputPath: target.outputPath,
    action: "generated",
    typeCount: schemas.length,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const schemas = collectSchemas();

  if (schemas.length === 0) {
    console.log("No schema files found in upstream/ or authored/.");
    console.log("Run 'npm run sync-upstream' first to fetch upstream schemas.");
    process.exit(0);
  }

  console.log(`Found ${schemas.length} schema(s):`);
  for (const s of schemas) {
    console.log(`  - ${s.name}`);
  }
  console.log();

  const results: GenerationResult[] = [];

  for (const target of LANGUAGES) {
    const result = await generateForLanguage(target, schemas);
    results.push(result);
  }

  // Print summary
  console.log("--- generate-bindings summary ---\n");
  for (const r of results) {
    if (r.action === "generated") {
      console.log(
        `  GENERATED  ${r.lang.padEnd(12)} → ${r.outputPath}  (${r.typeCount} type(s))`
      );
    } else {
      console.log(`  skipped    ${r.lang.padEnd(12)}   ${r.reason}`);
    }
  }

  const generatedCount = results.filter((r) => r.action === "generated").length;
  const skippedCount = results.filter((r) => r.action === "skipped").length;
  console.log(
    `\n${generatedCount} language(s) generated, ${skippedCount} skipped.`
  );
}

main().catch((error: unknown) => {
  console.error(
    "generate-bindings failed:",
    error instanceof Error ? error.message : error
  );
  process.exit(1);
});
