#!/usr/bin/env tsx
// Copyright Ben Chatelain. Apache 2.0

/**
 * Generates typed language bindings from JSON Schema files.
 *
 * Collects schemas from:
 *   - `upstream/` (top-level .json files only)
 *   - `authored/` (.json files, excluding `_meta/`)
 *
 * For each target language (Go, TypeScript, Python, Rust), runs quicktype-core
 * to produce typed code and writes the output to `generated/<lang>/`.
 *
 * Languages whose output directory does not exist are silently skipped.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  InputData,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
  quicktype,
} from "quicktype-core";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");
const UPSTREAM_DIR = join(PROJECT_ROOT, "upstream");
const AUTHORED_DIR = join(PROJECT_ROOT, "authored");
const GENERATED_DIR =
  process.env["GENERATE_OUTPUT_DIR"] ?? join(PROJECT_ROOT, "generated");

// ---------------------------------------------------------------------------
// Language configuration
// ---------------------------------------------------------------------------

interface ScaffoldFile {
  path: string;
  content: string;
}

interface LanguageTarget {
  /** quicktype language identifier (must match a quicktype built-in name) */
  lang: "go" | "typescript" | "python" | "rust";
  /** Output file path relative to GENERATED_DIR */
  outputPath: string;
  /** quicktype rendererOptions */
  rendererOptions: Record<string, string>;
  /** Comment syntax for the generated-by header */
  commentHeader: string;
  /** Auxiliary files written alongside the generated types */
  scaffoldFiles?: ScaffoldFile[];
}

const LANGUAGES: readonly LanguageTarget[] = [
  {
    lang: "go",
    outputPath: "go/types.go",
    rendererOptions: { package: "claudeconfig" },
    commentHeader:
      "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
    scaffoldFiles: [
      {
        path: "go/go.mod",
        content: [
          "module github.com/phatblat/claude-config-schema/generated/go",
          "",
          "go 1.22",
          "",
        ].join("\n"),
      },
    ],
  },
  {
    lang: "typescript",
    outputPath: "ts/src/types.ts",
    rendererOptions: {},
    commentHeader:
      "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
    scaffoldFiles: [
      {
        path: "ts/package.json",
        content:
          JSON.stringify(
            {
              name: "@phatblat/claude-code-config",
              version: "0.0.0",
              description:
                "TypeScript types for Claude Code configuration surfaces",
              type: "module",
              main: "dist/types.js",
              types: "dist/types.d.ts",
              files: ["dist"],
              scripts: { build: "tsc", prepublishOnly: "tsc" },
              devDependencies: { typescript: "^5.8.3" },
              license: "MIT",
            },
            null,
            2
          ) + "\n",
      },
      {
        path: "ts/tsconfig.json",
        content:
          JSON.stringify(
            {
              compilerOptions: {
                target: "ES2022",
                module: "Node16",
                moduleResolution: "Node16",
                declaration: true,
                strict: false,
                skipLibCheck: true,
                outDir: "dist",
                rootDir: "src",
              },
              include: ["src/**/*.ts"],
            },
            null,
            2
          ) + "\n",
      },
    ],
  },
  {
    lang: "python",
    outputPath: "python/claude_config/types.py",
    rendererOptions: {},
    commentHeader:
      "# Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
    scaffoldFiles: [
      {
        path: "python/pyproject.toml",
        content: [
          "[build-system]",
          'requires = ["setuptools>=68.0"]',
          'build-backend = "setuptools.build_meta"',
          "",
          "[project]",
          'name = "claude-code-config"',
          'version = "0.0.0"',
          'description = "Python types for Claude Code configuration surfaces"',
          'requires-python = ">=3.10"',
          'license = "MIT"',
          "",
          "[tool.setuptools.packages.find]",
          'include = ["claude_config*"]',
          "",
        ].join("\n"),
      },
      {
        path: "python/claude_config/__init__.py",
        content:
          "# Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.\n",
      },
    ],
  },
  {
    lang: "rust",
    outputPath: "rust/src/types.rs",
    rendererOptions: {},
    commentHeader:
      "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
    scaffoldFiles: [
      {
        path: "rust/Cargo.toml",
        content: [
          "[package]",
          'name = "claude-code-config"',
          'version = "0.0.0"',
          'edition = "2021"',
          'description = "Rust types for Claude Code configuration surfaces"',
          'license = "MIT"',
          "",
          "[dependencies]",
          'serde = { version = "1", features = ["derive"] }',
          'serde_json = "1"',
          "",
        ].join("\n"),
      },
      {
        path: "rust/src/lib.rs",
        content: [
          "// Code generated by generate-bindings.ts from JSON Schema. DO NOT EDIT.",
          "",
          "mod types;",
          "pub use types::*;",
          "",
        ].join("\n"),
      },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Derives a PascalCase type name from a schema filename.
 *
 * Examples:
 *   settings.json       → Settings
 *   plugin-manifest.json → PluginManifest
 *   skill-frontmatter.json → SkillFrontmatter
 */
function deriveTypeName(filename: string): string {
  const base = filename.replace(/\.json$/, "");
  return base
    .split("-")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

/**
 * Collects schema entries from upstream/ (top-level .json only) and
 * authored/ (.json files, excluding _meta/).
 */
function collectSchemas(): Array<{ name: string; schema: string }> {
  const schemas: Array<{ name: string; schema: string }> = [];

  // Upstream: top-level .json files only
  if (existsSync(UPSTREAM_DIR)) {
    const entries = readdirSync(UPSTREAM_DIR, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".json")) {
        const filePath = join(UPSTREAM_DIR, entry.name);
        const typeName = deriveTypeName(entry.name);
        schemas.push({
          name: typeName,
          schema: readFileSync(filePath, "utf-8"),
        });
      }
    }
  }

  // Authored: .json files recursively, excluding _meta/
  if (existsSync(AUTHORED_DIR)) {
    collectAuthoredSchemas(AUTHORED_DIR, schemas);
  }

  return schemas;
}

function collectAuthoredSchemas(
  dir: string,
  schemas: Array<{ name: string; schema: string }>
): void {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip the _meta directory
      if (entry.name === "_meta") continue;
      collectAuthoredSchemas(fullPath, schemas);
    } else if (entry.isFile() && entry.name.endsWith(".json")) {
      const typeName = deriveTypeName(entry.name);
      schemas.push({
        name: typeName,
        schema: readFileSync(fullPath, "utf-8"),
      });
    }
  }
}

/**
 * Ensures the parent directory for a file path exists.
 */
function ensureParentDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

interface GenerationResult {
  lang: string;
  outputPath: string;
  typeCount: number;
}

async function generateForLanguage(
  target: LanguageTarget,
  schemas: ReadonlyArray<{ name: string; schema: string }>
): Promise<GenerationResult> {
  const outputFile = join(GENERATED_DIR, target.outputPath);
  const outputDir = dirname(outputFile);

  // Create the output directory if it doesn't exist
  mkdirSync(outputDir, { recursive: true });

  const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());

  for (const { name, schema } of schemas) {
    await schemaInput.addSource({ name, schema });
  }

  const inputData = new InputData();
  inputData.addInput(schemaInput);

  const result = await quicktype({
    inputData,
    lang: target.lang,
    rendererOptions: target.rendererOptions,
  });

  const content =
    target.commentHeader + "\n\n" + result.lines.join("\n") + "\n";

  ensureParentDir(outputFile);
  writeFileSync(outputFile, content);

  if (target.scaffoldFiles) {
    for (const sf of target.scaffoldFiles) {
      const sfPath = join(GENERATED_DIR, sf.path);
      ensureParentDir(sfPath);
      writeFileSync(sfPath, sf.content);
    }
  }

  return {
    lang: target.lang,
    outputPath: target.outputPath,
    typeCount: schemas.length,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const schemas = collectSchemas();

  if (schemas.length === 0) {
    console.log("No schema files found in upstream/ or authored/.");
    console.log("Run 'npm run sync-upstream' first to fetch upstream schemas.");
    process.exit(0);
  }

  console.log(`Found ${schemas.length} schema(s):`);
  for (const s of schemas) {
    console.log(`  - ${s.name}`);
  }
  console.log();

  const results: GenerationResult[] = [];

  for (const target of LANGUAGES) {
    const result = await generateForLanguage(target, schemas);
    results.push(result);
  }

  console.log("--- generate-bindings summary ---\n");
  for (const r of results) {
    console.log(
      `  GENERATED  ${r.lang.padEnd(12)} → ${r.outputPath}  (${r.typeCount} type(s))`
    );
  }
  console.log(`\n${results.length} language(s) generated.`);
}

main().catch((error: unknown) => {
  console.error(
    "generate-bindings failed:",
    error instanceof Error ? error.message : error
  );
  process.exit(1);
});
